import ENV from '@self/config/config.json'
import SELF from '@self/config/language'

const CONFIG = {
  network_error: ['网络状态异常', '網絡狀態異常', 'Abnormal Network Status'],
  network_timeout: ['网络请求超时', '網絡請求超時', 'Network request timeout'],
  try_later: ['请稍后重试', '請稍後重試', 'Please try again later'],
  state_info: ['状态信息', '狀態信息', 'State information'],
  no_error: ['无错误信息', '無錯誤信息', 'No error message'],
  cgi_error: ['接口错误', '接口錯誤', 'Interface error'],
  error_msg: ['错误信息', '錯誤信息', 'The error message'],
  nothing: ['无', '無', 'nothing'],
  warn_prompt: ['温馨提示', '溫馨提示', 'Warm prompt'],
  confirm: ['确定', '確定', 'confirm'],
  cancel: ['取消', '取消', 'cancel'],
  upload_format: ['只能上传 JPG 或 PNG 格式的图片', '只能上傳 JPG 或 PNG 格式的圖片', 'Only JPG or PNG images can be uploaded'],
  upload_max_size: ['选择的文件不得大于 2 MB', '選擇的文件不得大於 2 MB', 'The selected file must not be larger than 2 MB'],
  password_change: ['修改密码', '修改密碼', 'Change the password'],
  password_old: ['请输入旧密码', '請輸入舊密碼', 'Please enter your old password'],
  password_new: ['请输入新密码', '請輸入新密碼', 'Please enter a new password'],
  password_new_again: ['请再次输入新密码', '請再次輸入新密碼', 'Please enter the new password again'],
  submit: ['提交', '提交', 'Submit'],
  logout: ['注销登录', '註銷登錄', 'Log out'],
  password_same: ['新旧密码不得一致', '新舊密碼不得一致', 'The old and new passwords are inconsistent'],
  password_size: ['密码长度不得小于六位', '密碼長度不得小於六位', 'The password must contain at least six characters'],
  password_diff: ['两次输入的密码不一致', '兩次輸入的密碼不一致', 'The entered passwords are inconsistent'],
  change_success: ['修改成功', '修改成功', 'Modify successfully'],
  sure_logout: ['确定要退出登录吗', '確定要退出登錄嗎', 'Are you sure you want to log out'],
  account_input: ['请输入登录帐号', '請輸入登錄帳號', 'Please enter your login account'],
  password_input: ['请输入登录密码', '請輸入登錄密碼', 'Please enter your login password'],
  login: ['登录', '登錄', 'Login'],
  cropper: ['图片裁剪', '圖片裁剪', 'Image cropping'],
  reload: ['刷新', '刷新', 'Reload'],
  search: ['搜索', '搜索', 'Search'],
  search_input: ['输入内容搜索', '輸入內容搜索', 'Input content search'],
  no_data: ['暂无数据', '暫無數據', 'Temporarily no data'],
  check_error: ['存在不符合条件的输入值，请检查', '存在不符合條件的輸入值，請檢查', 'The input value does not meet the requirements. Check the value'],
  input: ['请配置', '請配置', 'Please configure'],
  select: ['请选择', '請選擇', 'Please select'],
  submit_success: ['提交成功', '提交成功', 'Submitted successfully'],
  sure_delete: ['确定要执行删除操作吗', '確定要執行刪除操作嗎', 'Are you sure you want to delete'],
  editor_bold: ['加粗', '加粗', 'bold'],
  editor_italic: ['斜体', '斜體', 'italic'],
  editor_underline: ['下划线', '下劃線', 'underline'],
  editor_heading_1: ['H1', 'H1', 'H1'],
  editor_heading_2: ['H2', 'H2', 'H2'],
  editor_bullet: ['无序列表', '無序列表', 'bullet list'],
  editor_ordered: ['有序列表', '有序列表', 'ordered list'],
  editor_align_0: ['居左', '居左', 'align left'],
  editor_align_1: ['居中', '居中', 'align center'],
  editor_align_2: ['居右', '居右', 'align right'],
  editor_image: ['图片', '圖片', 'image'],
  editor_full: ['全屏', '全屏', 'full screen'],
  editor_exit: ['退出全屏', '退出全屏', 'Exit full screen'],
  add: ['添加', '添加', 'add'],
  edit: ['编辑', '編輯', 'edit'],
  create: ['新建', '新建', 'create'],
  handle: ['操作', '操作', 'handle'],
  config_id: ['配置标识', '配置標識', 'config id'],
  config_name: ['配置名称', '配置名稱', 'config name'],
  config_type: ['配置类型', '配置類型', 'config type'],
  config_content: ['配置内容', '配置內容', 'config content'],
  text: ['文本', '文本', 'text'],
  rich_text: ['富文本', '富文本', 'rich text'],
  system_config: ['系统配置', '系統配置', 'system config'],
  sort: ['排序', '排序', 'Sort']
}

const TYPE = ['cn', 'cht', 'en']
const LANG = { cn: {}, cht: {}, en: {} }

Object.keys(SELF).forEach(i => CONFIG[i] = SELF[i])
Object.keys(CONFIG).forEach(i => CONFIG[i].forEach((text, index) => LANG[TYPE[index]][i] = text))

export default LANG[TYPE.includes(ENV.lang) ? ENV.lang : TYPE[0]]
